### ISSUE TITLE
ZAP CAMERA IS NOT SUPPORTED ON IOS 14

### ISSUE THREAD

**Issue by marvystudio** [zappar-xr/zappar-unity-examples#3]
I've been making a test with instant tracking/image tracking WebAR using zap cemera, it worked fine on iOS13 but when i updated to <b>iOS14</b>, the only thing it shows is a blank white space. I attached the picture of the console log, saying it's unable to process frame.

<img width="1002" alt="Screen Shot 2020-09-18 at 3 55 56 PM" src="https://user-images.githubusercontent.com/51011256/93578378-7120bb00-f9c7-11ea-86e2-8c451d09f58a.png">

**Comment by cgauld** [comment]
Hi! We're in the process of preparing a general update of our Unity plugin that fixes this and should be available in the next few days. In the mean time we have a workaround that should get you back up and running straight away.

Try editing the following file:
`Assets/Plugins/zcv.jslib`
Around line 17, change the URL to `https://libs.zappar.com/zappar-cv/0.2.11/zappar-cv.js`
That version of the underlying computer vision library has the iOS 14 fixes.

Let us know if that sorts things out!
