### ISSUE TITLE
LONG WHITE SPACE LOADING AT LAUNCH ZAPWORKS AR EFFECT

### ISSUE THREAD

**Issue by marvystudio** [zappar-xr/zappar-unity-examples#4]
Hi,

I built a project using Zapworks SDK for Unity on iOS14 and there's a long white screen after clicking grant access button. It takes around 5-10 second to open the camera.
Please help

Thanks!

**Comment by nyan-left** [comment]
Hi there!

I suspect you're experiencing the white screen as the assets are still downloading for your app. 

Check out `ZapparCameraBackground.cs` which carries out the checks to see if a camera texture is available. 
The script contains `m_hasInitialised` (tells us if the Zappar library is loading) alongside `m_currentTexture` which is false when the camera texture is not yet available. I would recommend building a loading screen which tells your users that assets are being downloaded. 

Alternatively, an easier route - you may also swap out the `ZapparCameraBackground` material (default white) for an image which asks your users to hang tight as the experience loads.

Hope this helps.

**Comment by nyan-left** [comment]
Fixed with 0.2.8
