### ISSUE TITLE
UAR incompatible with 2020 WebGL builds, even with Zappar2020 template.

### ISSUE THREAD

**Issue by marcusx2** [zappar-xr/zappar-unity-examples#5]
When I open the project with Unity 2020, I get this:

https://zapworksforumuploads.s3.dualstack.eu-west-1.amazonaws.com/original/2X/c/c10b758dc35ae62d8c9dc6f71e110cc6ed60338a.png

Then when I try to build, I get this(with the Zappar2020 template selected):

https://zapworksforumuploads.s3.dualstack.eu-west-1.amazonaws.com/original/2X/9/923759e87f8f2d396b89aac2676e4dc2510eb2ef.png

This is all just with Unity 2020, it builds fine with 2019.

**Comment by nfynt-zap** [comment]
Should be fixed now!
