### ISSUE TITLE
3d model not showing on Image Tracking 3D animation example.

### ISSUE THREAD

**Issue by marcusx2** [zappar-xr/zappar-unity-examples#6]
It's simply not showing anymore.

Please see this thread: https://forum.zap.works/t/universalar-unity-webgl-not-working

It shows the progress regarding the bugs on this example. Before it was showing but the 3d model was not facing me. Now the model is just gone lol ;_;. The example was almost fixed and now it's completely unusable T_T.

**Comment by nfynt-zap** [comment]
Should be fixed now!
